version: '3.7'
name: sleepr_prod

services:


  
  mongo:
    image: mongo:7
    ports:
      - "27016:27017"
    volumes:
      - mongo_data_prod:/data/db

  reservations:
    env_file:
      - .env.prod
    build:
      dockerfile: apps/reservations/prod.Dockerfile
    ports:
      - "3000:3000"
    command: node /app/dist/index.js


  auth:
    env_file:
      - .env.prod
    build:
      dockerfile: apps/auth/prod.Dockerfile
    ports:
      - "3011:3011"
      - "3010:3010"
    command: node /app/dist/index.js

  payments:
    env_file:
      - .env.prod
    build:
      dockerfile: apps/payments/prod.Dockerfile
    ports:
      - "3020:3020"
      - "3021:3021"
    command: node /app/dist/index.js

  notifications:
    env_file:
      - .env.prod
    build:
      dockerfile: apps/notifications/prod.Dockerfile
    ports:
      - "3031:3031"
      - "3030:3030"
    command: node /app/dist/index.js


volumes:
  mongo_data_prod:
