version: '3.7'

name: sleepr_local

services:

  postgres:
    image: postgres:16-alpine
    ports:
      - "5431:5432"
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  reservations:
    depends_on:
      - postgres
    volumes:
      - ./apps:/app/apps/
      - ./libs:/app/libs/
    env_file:
      - .env.prod
    build:
      dockerfile: local.Dockerfile
    ports:
      - "3000:3000"
      - "9228:9228"
    command: |
      sh -c "
       cp -r /app/apps/reservations/prisma /app/prisma && \
       cat /app/apps/reservations/.env > /app/.env && \
       pnpm prisma generate --schema /app/prisma/schema.prisma && \
       pnpm prisma migrate deploy --schema /app/prisma/schema.prisma && \
       npm run reservations
      "

  auth:
    volumes:
      - ./apps:/app/apps/
      - ./libs:/app/libs/
    env_file:
      - .env.prod
    build:
      dockerfile: local.Dockerfile
    command: |
      sh -c "
       cp -r /app/apps/auth/prisma /app/prisma && \
       cat /app/apps/auth/.env > /app/.env && \
       pnpm prisma generate --schema /app/prisma/schema.prisma && \
       pnpm prisma migrate deploy --schema /app/prisma/schema.prisma && \
       npm run auth
      "
    ports:
      - "3011:3011"
      - "3010:3010"
      - "9229:9229"

  payments:
    volumes:
      - ./apps:/app/apps/
      - ./libs:/app/libs/
    env_file:
      - .env.prod
    build:
      dockerfile: local.Dockerfile
    command: npm run payments
    ports:
      - "3020:3020"
      - "3021:3021"
      - "9227:9227"

  notifications:
    volumes:
      - ./apps:/app/apps/
      - ./libs:/app/libs/
    env_file:
      - .env.prod
    build:
      dockerfile: local.Dockerfile
    command: npm run notifications
    ports:
      - "3031:3031"
      - "3030:3030"
      - "9226:9226"

volumes:
  postgres_data:
