version: '3.7'
name: sleepr_flex

services:

  mongo:
    image: mongo:7
    ports:
      - "27000:27017"
    volumes:
      - mongo_data:/data/db

  reservations:
    env_file:
      - .env.prod
    build:
      dockerfile: apps/reservations/debug.Dockerfile
    ports:
      - "27000:3000"
    command: node /app/dist/apps/reservations/src/main

  auth:
    env_file:
      - .env.prod
    build:
      dockerfile: apps/auth/debug.Dockerfile
    ports:
      - "27011:3011"
      - "27010:3010"
    command: node /app/dist/apps/auth/src/main.js

  payments:
    env_file:
      - .env.prod
    build:
      dockerfile: apps/payments/debug.Dockerfile
    ports:
      - "27020:3020"
      - "27021:3021"
    command: node /app/dist/apps/payments/src/main.js


volumes:
  mongo_data:
