version: '3.7'
name: sleepr_prod

services:

  
  mongo:
    image: mongo:7
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: your_password_here
    volumes:
      - mongo_data_prod:/data/db

  reservations:
    restart: always
    env_file:
      - .env
    build:
      dockerfile: apps/reservations/prod.Dockerfile
    ports:
      - "3000:3000"
    command: node /app/dist/index.js


  auth:
    restart: always
    env_file:
      - .env
    build:
      dockerfile: apps/auth/prod.Dockerfile
    ports:
      - "3010:3010"
    command: node /app/dist/index.js

  payments:
    restart: always
    env_file:
      - .env
    build:
      dockerfile: apps/payments/prod.Dockerfile
    command: node /app/dist/index.js

  notifications:
    restart: always
    env_file:
      - .env
    build:
      dockerfile: apps/notifications/prod.Dockerfile
    command: node /app/dist/index.js


volumes:
  mongo_data_prod:
