apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      name: auth
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: europe-west10-docker.pkg.dev/sleepr-423612/sleepr/app:latest
          imagePullPolicy: Never
          command: [ "node", "/app/dist/apps/auth/src/main" ]
          envFrom:
            - configMapRef:
                name: mongo-env-config