apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: "auth-tcp"
      protocol: TCP
      port: 3011
      targetPort: 3011


---

apiVersion: v1
kind: Service
metadata:
  name: auth-http
spec:
  selector:
    app: auth
  ports:
    - name: "auth-http"
      protocol: TCP
      port: 3010
      targetPort: 3010
      nodePort: 30010
  type: NodePort
