apiVersion: v1
kind: Service
metadata:
  name: reservations
spec:
  selector:
    app: reservations
  ports:
    - name: 'http'
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
  